receivers:
  faro:
    endpoint: 0.0.0.0:12347

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

processors:
  batch:
    timeout: 5s
    send_batch_size: 100

service:
  pipelines:
    traces:
      receivers: [faro]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [faro]
      processors: [batch]
      exporters: [loki]
